/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

/**
 *
 * @author Temis juninho
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caixadetextoUsuario = new javax.swing.JTextField();
        caixadetextosenha = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        textoSenha = new javax.swing.JLabel();
        TextoUsuario = new javax.swing.JLabel();
        imagendeprediosdeitado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        caixadetextoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixadetextoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(caixadetextoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 230, 40));

        caixadetextosenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixadetextosenhaActionPerformed(evt);
            }
        });
        getContentPane().add(caixadetextosenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 230, 40));

        jButton1.setText("Entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 290, 110, -1));

        textoSenha.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        textoSenha.setForeground(new java.awt.Color(255, 255, 255));
        textoSenha.setText("Senha");
        getContentPane().add(textoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 80, -1));

        TextoUsuario.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        TextoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        TextoUsuario.setText("Usuario");
        getContentPane().add(TextoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        imagendeprediosdeitado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/prediosnocrepusculodeitado.jpg"))); // NOI18N
        getContentPane().add(imagendeprediosdeitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 2080, -1));

        jMenu1.setText("Registrar");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/registrar.png"))); // NOI18N
        jMenuItem1.setText("Registrar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caixadetextoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixadetextoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixadetextoUsuarioActionPerformed

    private void caixadetextosenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixadetextosenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixadetextosenhaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextoUsuario;
    private javax.swing.JTextField caixadetextoUsuario;
    private javax.swing.JPasswordField caixadetextosenha;
    private javax.swing.JLabel imagendeprediosdeitado;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel textoSenha;
    // End of variables declaration//GEN-END:variables
}
